var COMMANDS  = { "en" : {
        "voice" : "UK English Female",
        "default" : 'Say "What can I say?" to see a list of commands...',
        "hi" : 'Hi, sexy!',
        "whatcanisay" : 'What can I say',
        "home" : 'Go home',
        "sleep" : 'Go to sleep',
        "wake" : 'Wake up',
        "debug" : 'Show debug information',
        "map" : 'Show map',
        "locaiton" : 'Show (me a) map of *location',
        "zoomin" : '(map) zoom in',
        "zoomout" : '(map) zoom out',
        "zoomvalue" : '(map) zoom (to) *value',
        "zoomreset" : '(map) reset zoom',
        "term" : 'Show me *term',
        "name" : 'My (name is)(name\'s) *name',
        "task" : 'Remind me to *task',
        "reminder" : 'Clear reminders',
        "clear" : 'Clear results',
        "time" : 'what time is it',
        "light" : '(turn) (the) :state (the) light(s) *action',
        "playyoutube" : 'play *term youtube',
        "ytbplaylist" : '*term playlist',
        "stopyoutube" : 'stop youtube',
        "subway" : 'show me *linenumber info at *station',
        "musicplay" : "play music *track",
        "musicreplay" : "replay music",
        "musicresume" : "resume music",
        "musicstop" : "stop music",
        "info" :  "Here is a list of commands..."
    },
    "ko" : {
        "voice" : "Korean Female",
        "default" : '"사용 가능한 질문" 이라 말해 보세요',
        "hi" : '안녕 Zele',
        "whatcanisay" : '사용 가능한 질문',
        "home" : '(홈으로)(메인 화면)',
        "sleep" : '잠자러가',
        "wake" : '일어나',
        "debug" : '디버그 정보 보여 줘',
        "term" : '*term 보여 줘',
        "name" : '나(는)(의 이름은) *name야',
        "task" : '*task 상기 시켜 줘',
        "reminder" : '리마인더 제거해 줘',
        "clear" : '결과 없애 줘',
        "time" : '지금 몇 시',
        "info" : "다음은 사용 가능한 질문입니다.",
        "news" : "뉴스 보여 줘"
    }
};
